name: Deploy Docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MkDocs
        run: pip install mkdocs
      - name: Deploy
        run: mkdocs gh-deploy --force
